package GODOT::local::CatalogueHoldings::BibCirc::BVAU;
##
## Copyright (c) 2005, Kristina Long, Simon Fraser University
##
use GODOT::CatalogueHoldings::BibCirc::Z3950::ENDEAVOR;
@ISA = qw(GODOT::CatalogueHoldings::BibCirc::Z3950::ENDEAVOR);

use GODOT::String;
use GODOT::Object;
use GODOT::CatalogueHoldings::BibCirc;
use CGI qw(:escape);

use strict;

##
## (02-feb-2006 kl) - they have separate machines for Z39.50 and the web interface
##

sub cat_url {
    my($self, $host) = @_;
    
    return $self->SUPER::cat_url('webcat1.library.ubc.ca');
}


#### sub only_circ_in_short_journal_rec { return $TRUE; }



sub location_to_site {
    my($self, $location) = @_;

    return $self->SUPER::location_to_site(uc($location));
}

sub circ_location_to_site {
    my($self, $location) = @_;
 
    my $site = $self->site;

    ## 
    ## -use same data for holdings (ie. summary) and circ locations
    ##
    $site = $self->location_to_site(uc(trim_beg_end($location)));
  
    return $site;
}


sub _skip_hacd_enum_and_chron  { return $TRUE; }

sub _site {
    my($self, $location, $nuc) = @_;

    return $location;
}

sub _location_to_site_map {

    my %map = (
        "ASIAN LIBRARY STACKS"                                            => 'BVAU-AS',
        "ASIAN LIBRARY JOURNALS"                                          => 'BVAU-AS',
        "ASIAN LIBRARY AUDIO-VISUAL"                                      => 'BVAU-AS',
        "ASIAN LIBRARY CD STATION (NON-CIRCULATING)"                      => 'BVAU-AS',
        "ASIAN LIBRARY REFERENCE (NON-CIRCULATING)"                       => 'BVAU-AS',
        "ASIAN LIBRARY STAFF AREA"                                        => 'BVAU-AS',
        "ASIAN LIBRARY OVERSIZE"                                          => 'BVAU-AS',
        "ASIAN LIBRARY RESERVE COLLECTION"                                => 'BVAU-AS',
        "ASIAN LIBRARY INDIC COLLECTION"                                  => 'BVAU-AS',
        "ASIAN LIBRARY INDIC REFERENCE (NON-CIRCULATING)"                 => 'BVAU-AS',
        "ASIAN LIBRARY PUBAN COLLECTION (NON-CIRCULATING)"                => 'BVAU-AS',
        "ASIAN LIBRARY RARE BOOKS (NON-CIRCULATING)"                      => 'BVAU-AS',
        "ASIAN LIBRARY SOUTHEAST ASIAN COLLECTION"                        => 'BVAU-AS',
        "ASIAN LIBRARY SOUTHEAST ASIAN REFERENCE (NON-CIRCULATING)"       => 'BVAU-AS',
        "ASIAN LIBRARY SOUTHEAST ASIAN JOURNALS"                          => 'BVAU-AS',
        "ASIAN LIBRARY INDIC JOURNALS"                                    => 'BVAU-AS',
        "ASIAN LIBRARY STORAGE"                                           => 'BVAU-AS',
        "ASIAN LIBRARY CIRCULATION DESK"                                  => 'BVAU-AS',
        "ASIAN LIBRARY DAMAGED"                                           => 'BVAU-AS',
        "BMB LIBRARY 700 W 10TH STACKS"                                   => 'BVAU-BMB',
        "BMB LIBRARY 700 W 10TH REFERENCE (NON-CIRCULATING)"              => 'BVAU-BMB',
        "BMB LIBRARY 700 W 10TH JOURNALS (NON-CIRCULATING)"               => 'BVAU-BMB',
        "BMB LIBRARY 700 W 10TH CIRCULATION DESK"                         => 'BVAU-BMB',
        "BMB LIBRARY 700 W 10TH DAMAGED"                                  => 'BVAU-BMB',
        "DAVID LAM LIBRARY STACKS"                                        => 'BVAU-DLAM',
        "DAVID LAM LIBRARY CD STATION (NON-CIRCULATING)"                  => 'BVAU-DLAM',
        "DAVID LAM LIBRARY REFERENCE (NON-CIRCULATING)"                   => 'BVAU-DLAM',
        "DAVID LAM LIBRARY JOURNALS (NON-CIRCULATING)"                    => 'BVAU-DLAM',
        "DAVID LAM LIBRARY MICROFORMS"                                    => 'BVAU-DLAM',
        "DAVID LAM LIBRARY AUDIO-VISUAL"                                  => 'BVAU-DLAM',
        "DAVID LAM LIBRARY GOV PUBS"                                      => 'BVAU-DLAM',
        "DAVID LAM LIBRARY INDEXES & ABSTRACTS (NON-CIRCULATING)"         => 'BVAU-DLAM',
        "DAVID LAM LIBRARY NEWSPAPERS"                                    => 'BVAU-DLAM',
        "DAVID LAM LIBRARY STATISTICS CANADA"                             => 'BVAU-DLAM',
        "DAVID LAM LIBRARY CIRCULATION DESK"                              => 'BVAU-DLAM',
        "DAVID LAM LIBRARY RESERVE COLLECTION"                            => 'BVAU-DLAM',
        "DAVID LAM LIBRARY DAMAGED"                                       => 'BVAU-DLAM',
        "EDUCATION LIBRARY STACKS"                                        => 'BVAU-EL',
        "EDUCATION LIBRARY MICROFORMS"                                    => 'BVAU-EL',
        "EDUCATION LIBRARY OVERSIZE"                                      => 'BVAU-EL',
        "EDUCATION LIBRARY RESERVE COLLECTION"                            => 'BVAU-EL',
        "EDUCATION LIBRARY CDN CHILDRENS BOOK CTR COLLECTION"             => 'BVAU-EL',
        "EDUCATION LIBRARY FRENCH COLLECTION"                             => 'BVAU-EL',
        "EDUCATION LIBRARY BC AUTHORS"                                    => 'BVAU-EL',
        "EDUCATION LIBRARY CD STATION (NON-CIRCULATING)"                  => 'BVAU-EL',
        "EDUCATION LIBRARY HISTORICAL TEXTBOOKS COLLECTION"               => 'BVAU-EL',
        "EDUCATION LIBRARY JOURNALS (NON-CIRCULATING)"                    => 'BVAU-EL',
        "EDUCATION LIBRARY REFERENCE (NON-CIRCULATING)"                   => 'BVAU-EL',
        "EDUCATION LIBRARY VIDEOS"                                        => 'BVAU-EL',
        "EDUCATION LIBRARY CIRCULATION DESK"                              => 'BVAU-EL',
        "EDUCATION LIBRARY DAMAGED"                                       => 'BVAU-EL',
        "EDUCATION LIBRARY STAFF AREA"                                    => 'BVAU-EL',
        "HAMBER LIBRARY REFERENCE (NON-CIRCULATING)"                      => 'BVAU-HAMB',
        "HAMBER LIBRARY C&W EDUCATIONAL COLLECTION"                       => 'BVAU-HAMB',
        "HAMBER LIBRARY STORAGE"                                          => 'BVAU-HAMB',
        "HAMBER LIBRARY STACKS"                                           => 'BVAU-HAMB',
        "HAMBER LIBRARY LIBRARIAN'S OFFICE"                               => 'BVAU-HAMB',
        "HAMBER LIBRARY RESERVE COLLECTION"                               => 'BVAU-HAMB',
        "HAMBER LIBRARY CIRCULATION DESK"                                 => 'BVAU-HAMB',
        "HAMBER LIBRARY DICTIONARY & DIRECTORY (NON-CIRCULATING)"         => 'BVAU-HAMB',
        "HAMBER LIBRARY DAMAGED"                                          => 'BVAU-HAMB',
        "HAMBER LIBRARY JOURNALS"                                         => 'BVAU-HAMB',
        "DATA CLEANUP LOCATION"                                           => 'BVAU-KRNR',
        "KOERNER LIBRARY RESERVE COLLECTION (FLOOR 3)"                    => 'BVAU-KRNR',
        "EXTENSION LIBRARY STAFF AREA"                                    => 'BVAU-KRNR',
        "KOERNER LIBRARY INTERLIBRARY LOANS (FLOOR 2)"                    => 'BVAU-KRNR',
        "KOERNER LIBRARY GOV PUBS (FLOOR 2)"                              => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE CD STATION (FLOOR 2)"                  => 'BVAU-KRNR',
        "KOERNER LIBRARY VERTICAL FILE (NON-CIRCULATING) (FLOOR 2)"       => 'BVAU-KRNR',
        "KOERNER LIBRARY GOV PUBS STATISTICS CANADA (FLOOR 2)"            => 'BVAU-KRNR',
        "KOERNER LIBRARY STACKS"                                          => 'BVAU-KRNR',
        "KOERNER LIBRARY FILM STORAGE (FLOOR 2)"                          => 'BVAU-KRNR',
        "KOERNER LIBRARY NEWSPAPERS (NON-CIRCULATING) (FLOOR 2)"          => 'BVAU-KRNR',
        "KOERNER LIBRARY CURRENT JOURNALS (FLOOR 2)"                      => 'BVAU-KRNR',
        "KOERNER LIBRARY MICROFORMS (FLOOR 2)"                            => 'BVAU-KRNR',
        "KOERNER LIBRARY MICROFORMS REFERENCE MICROFORMS (FLOOR 2)"       => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE (NON-CIRCULATING) (FLOOR 2)"           => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE INDEXES & ABSTRACTS (FLOOR 2)"         => 'BVAU-KRNR',
        "KOERNER LIBRARY QUICK REFERENCE (FLOOR 2)"                       => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE THEMATIC MAPS (FLOOR 2)"               => 'BVAU-KRNR',
        "LPC CATALOGUIING"                                                => 'BVAU-KRNR',
        "CATALOGUING REFERENCE"                                           => 'BVAU-KRNR',
        "LPC SERIALS"                                                     => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE CD STATION (FLOOR 2)"                => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE (FLOOR 2)"                           => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE ATLASES (FLOOR 2)"                   => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE LINGUISTIC ATLASES (FLOOR 2)"        => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE THEMATIC MAPS (FLOOR 2)"             => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE TOPOGRAPHIC MAPS (FLOOR 2)"          => 'BVAU-KRNR',
        "PRESERVATION OFFICE"                                             => 'BVAU-KRNR',
        "KOERNER LIBRARY PATSCAN OFFICE (FLOOR 2)"                        => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS"                                => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS REFERENCE"                      => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS MICROFORMS"                     => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS STAFF AREA"                     => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS OVERSIZE"                       => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS PAMPHLET FILES"                 => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS POLISH PUBLICATIONS"            => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS SOCIAL WORK COLLECTION"         => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS UBC ESSAYS"                     => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS JAPANESE MAPS"                  => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS MAPS"                           => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS STORAGE (LPC)"                  => 'BVAU-KRNR',
        "LPC STORAGE B"                                                   => 'BVAU-KRNR',
        "LPC STORAGE A"                                                   => 'BVAU-KRNR',
        "KOERNER LIBRARY MICROFORMS STORAGE (FLOOR 2)"                    => 'BVAU-KRNR',
        "RARE BOOKS & SPECIAL COLLECTIONS STORAGE"                        => 'BVAU-KRNR',
        "KOERNER LIBRARY MICROFORMS MUSIC STORAGE (FLOOR 2)"              => 'BVAU-KRNR',
        "SYSTEMS (NON-CIRCULATING)"                                       => 'BVAU-KRNR',
        "WITHDRAWN"                                                       => 'BVAU-KRNR',
        "TRIUMF"                                                          => 'BVAU-KRNR',
        "ONLINE"                                                          => 'BVAU-KRNR',
        "XWI7XWA LIBRARY STACKS"                                          => 'BVAU-KRNR',
        "XWI7XWA LIBRARY AUDIO-VISUAL"                                    => 'BVAU-KRNR',
        "XWI7XWA LIBRARY REFERENCE (NON-CIRCULATING)"                     => 'BVAU-KRNR',
        "REVIEW"                                                          => 'BVAU-KRNR',
        "KOERNER LIBRARY CURRENT JOURNALS OFFICE (FLOOR 2)"               => 'BVAU-KRNR',
        "KOERNER LIBRARY DATA CODEBOOKS (FLOOR 2)"                        => 'BVAU-KRNR',
        "KOERNER LIBRARY DATA STAFF AREA (NON-CIRCULATING) (FLOOR 2)"     => 'BVAU-KRNR',
        "KOERNER LIBRARY GOV PUBS INDEXES & ABSTRACTS (FLOOR 2)"          => 'BVAU-KRNR',
        "KOERNER LIBRARY GOV PUBS JOURNALS (FLOOR 2)"                     => 'BVAU-KRNR',
        "KOERNER LIBRARY GOV PUBS UNITED NATIONS (FLOOR 2)"               => 'BVAU-KRNR',
        "KOERNER LIBRARY JOURNALS (NON-CIRCULATING) (FLOOR 1)"            => 'BVAU-KRNR',
        "KOERNER LIBRARY MICROFORMS REFERENCE (FLOOR 2)"                  => 'BVAU-KRNR',
        "KOERNER LIBRARY MICROFORMS VERTICAL FILE (FLOOR 2)"              => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE OVERSIZE ATLASES (FLOOR 2)"          => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE REFERENCE (FLOOR 2)"                 => 'BVAU-KRNR',
        "KOERNER LIBRARY OVERSIZE (FLOOR 6)"                              => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE ATLASES (NON CIRCULATING (FLOOR 2)"    => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE FOLDED MAPS (FLOOR 2)"                 => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE OVERSIZE (FLOOR 2)"                    => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE STAFF AREA (FLOOR 2)"                  => 'BVAU-KRNR',
        "KOERNER LIBRARY REFERENCE TOPOGRAPHIC MAPS (FLOOR 2)"            => 'BVAU-KRNR',
        "KOERNER LIBRARY VERTICAL FILE (FLOOR 2)"                         => 'BVAU-KRNR',
        "LPC ACQUISITIONS"                                                => 'BVAU-KRNR',
        "XWI7XWA LIBRARY ARCHIVES"                                        => 'BVAU-KRNR',
        "XWI7XWA LIBRARY JOURNALS (NON-CIRCULATING)"                      => 'BVAU-KRNR',
        "XWI7XWA LIBRARY SPECIAL COLLECTION"                              => 'BVAU-KRNR',
        "KOERNER LIBRARY CIRCULATION DESK (FLOOR 3)"                      => 'BVAU-KRNR',
        "LPC CIRCULATION DESK"                                            => 'BVAU-KRNR',
        "OPAC CIRCULATION DESK"                                           => 'BVAU-KRNR',
        "XWI7XWA LIBRARY CIRCULATION DESK"                                => 'BVAU-KRNR',
        "KOERNER LIBRARY MAP STORAGE FOLDED MAPS (FLOOR 2)"               => 'BVAU-KRNR',
        "XWI7XWA LIBRARY VERTICAL FILE"                                   => 'BVAU-KRNR',
        "ASIAN ACQ STREET ADDRESS"                                        => 'BVAU-KRNR',
        "ASIAN ACQ PO BOX"                                                => 'BVAU-KRNR',
        "ASIAN SERIALS STREET ADDRESS"                                    => 'BVAU-KRNR',
        "ASIAN SERIALS PO BOX"                                            => 'BVAU-KRNR',
        "ASIAN ACQ US PO BOX"                                             => 'BVAU-KRNR',
        "BMB ACQ STREET ADDRESS"                                          => 'BVAU-KRNR',
        "DAVID LAM SERIALS STREET"                                        => 'BVAU-KRNR',
        "DAVID LAM SERIALS PO BOX"                                        => 'BVAU-KRNR',
        "HAMBER ACQ STREET"                                               => 'BVAU-KRNR',
        "KOERNER GOV PUBS ACQ STREET"                                     => 'BVAU-KRNR',
        "KOERNER GOV PUBS ACQ PO BOX"                                     => 'BVAU-KRNR',
        "LAW ACQ SERIALS STREET"                                          => 'BVAU-KRNR',
        "LAW ACQ SERIALS PO BOX"                                          => 'BVAU-KRNR',
        "LPC ACQ STREET"                                                  => 'BVAU-KRNR',
        "LPC ACQ PO BOX"                                                  => 'BVAU-KRNR',
        "LPC SERIALS STREET"                                              => 'BVAU-KRNR',
        "LPC SERIALS PO BOX"                                              => 'BVAU-KRNR',
        "MAP STREET"                                                      => 'BVAU-KRNR',
        "ST PAUL'S ACQ STREET"                                            => 'BVAU-KRNR',
        "WOODWARD ACQ STREET"                                             => 'BVAU-KRNR',
        "WOODWARD ACQ PO BOX"                                             => 'BVAU-KRNR',
        "WOODWARD SERIALS STREET"                                         => 'BVAU-KRNR',
        "WOODWARD SERIALS PO BOX"                                         => 'BVAU-KRNR',
        "ROBSON SQUARE ACQ STREET"                                        => 'BVAU-KRNR',
        "XWI7XWA LIBRARY RESERVE COLLECTION"                              => 'BVAU-KRNR',
        "KOERNER LIBRARY DAMAGED"                                         => 'BVAU-KRNR',
        "XWI7XWA LIBRARY DAMAGED"                                         => 'BVAU-KRNR',
        "KOERNER LIBRARY SELFSERVE CIRCULATION"                           => 'BVAU-KRNR',
        "LAW LIBRARY CD STATION"                                          => 'BVAU-LAW',
        "LAW LIBRARY REFERENCE (NON-CIRCULATING)"                         => 'BVAU-LAW',
        "LAW LIBRARY JOURNALS"                                            => 'BVAU-LAW',
        "LAW LIBRARY MICROFORMS"                                          => 'BVAU-LAW',
        "LAW LIBRARY CHINESE COLLECTION"                                  => 'BVAU-LAW',
        "LAW LIBRARY HONG KONG COLLECTION"                                => 'BVAU-LAW',
        "LAW LIBRARY INDIC COLLECTION"                                    => 'BVAU-LAW',
        "LAW LIBRARY JAPANESE COLLECTION"                                 => 'BVAU-LAW',
        "LAW LIBRARY MACAO COLLECTION"                                    => 'BVAU-LAW',
        "LAW LIBRARY REPORTS"                                             => 'BVAU-LAW',
        "LAW LIBRARY SPECIAL COLLECTION"                                  => 'BVAU-LAW',
        "LAW LIBRARY TAIWANESE COLLECTION"                                => 'BVAU-LAW',
        "LAW LIBRARY STORAGE"                                             => 'BVAU-LAW',
        "LAW LIBRARY STACKS"                                              => 'BVAU-LAW',
        "LAW LIBRARY AUDIO-VISUAL"                                        => 'BVAU-LAW',
        "LAW LIBRARY FACULTY LIBRARY"                                     => 'BVAU-LAW',
        "LAW LIBRARY INDONESIAN COLLECTION"                               => 'BVAU-LAW',
        "LAW LIBRARY KOREAN COLLECTION"                                   => 'BVAU-LAW',
        "LAW LIBRARY PROCESSING"                                          => 'BVAU-LAW',
        "LAW LIBRARY RESERVE COLLECTION"                                  => 'BVAU-LAW',
        "LAW LIBRARY STATUTES"                                            => 'BVAU-LAW',
        "LAW LIBRARY CIRCULATION DESK"                                    => 'BVAU-LAW',
        "LAW LIBRARY DAMAGED"                                             => 'BVAU-LAW',
        "MATHEMATICS LIBRARY STACKS"                                      => 'BVAU-MATH',
        "MATHEMATICS LIBRARY JOURNALS"                                    => 'BVAU-MATH',
        "MATHEMATICS LIBRARY REFERENCE (NON-CIRCULATING)"                 => 'BVAU-MATH',
        "MATHEMATICS LIBRARY CIRCULATION DESK"                            => 'BVAU-MATH',
        "MATHEMATICS LIBRARY RESERVE COLLECTION"                          => 'BVAU-MATH',
        "MATHEMATICS LIBRARY DAMAGED"                                     => 'BVAU-MATH',
        "MACMILLAN LIBRARY AUDIO-VISUAL"                                  => 'BVAU-MCM',
        "MACMILLAN LIBRARY REFERENCE (NON-CIRCULATING)"                   => 'BVAU-MCM',
        "MACMILLAN LIBRARY CURRENT JOURNALS"                              => 'BVAU-MCM',
        "MAIN LIBRARY AUDIO-VISUAL"                                       => 'BVAU-MCM',
        "MAIN LIBRARY CIRCULATION STAFF AREA"                             => 'BVAU-MCM',
        "MAIN LIBRARY RESERVE COLLECTION"                                 => 'BVAU-MCM',
        "MAIN LIBRARY STORAGE (WILSON)"                                   => 'BVAU-MCM',
        "MAIN LIBRARY ASIAN COLLECTION"                                   => 'BVAU-MCM',
        "MAIN LIBRARY CHAPMAN LEARNING COMMONS"                           => 'BVAU-MCM',
        "MACMILLAN LIBRARY ANNEX"                                         => 'BVAU-MCM',
        "MACMILLAN LIBRARY CIRCULATION DESK"                              => 'BVAU-MCM',
        "MACMILLAN LIBRARY STACKS"                                        => 'BVAU-MCM',
        "MACMILLAN LIBRARY COPY ROOM"                                     => 'BVAU-MCM',
        "MACMILLAN LIBRARY OVERSIZE"                                      => 'BVAU-MCM',
        "MACMILLAN LIBRARY REFERENCE DICTIONARY (NON-CIRCULATING)"        => 'BVAU-MCM',
        "MACMILLAN LIBRARY RESERVE COLLECTION"                            => 'BVAU-MCM',
        "MACMILLAN LIBRARY DAMAGED"                                       => 'BVAU-MCM',
        "MAIN LIBRARY STACKS"                                             => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS VERTICAL FILE"                            => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS MICROFORMS"                               => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS OVERSIZE"                                 => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS CURRENT JOURNALS"                         => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS RARE 2 (NON-CIRCULATING)"                 => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS RARE 4 (NON-CIRCULATING)"                 => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS RARE 6 (NON-CIRCULATING)"                 => 'BVAU-MN',
        "MAIN LIBRARY SCIENCE & ENGINEERING REFERENCE"                    => 'BVAU-MN',
        "MAIN LIBRARY SCIENCE & ENGINEERING CD STATION"                   => 'BVAU-MN',
        "MAIN LIBRARY SCIENCE & ENGINEERING MICROFORMS"                   => 'BVAU-MN',
        "MAIN LIBRARY SCIENCE & ENGINEERING STAFF AREA"                   => 'BVAU-MN',
        "MAIN LIBRARY SCIENCE & ENGINEERING GOV PUBS"                     => 'BVAU-MN',
        "MAIN LIBRARY SCIENCE & ENGINEERING STANDARDS COLLECTION"         => 'BVAU-MN',
        "MAIN LIBRARY SCIENCE & ENGINEERING STORAGE"                      => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (MN)"                                       => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (MN1)"                                      => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (MN2)"                                      => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (MN7)"                                      => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (MNA)"                                      => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (MNF)"                                      => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (MNK)"                                      => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (MONOS)"                                    => 'BVAU-MN',
        "MAIN LIBRARY STORAGE (SERIALS)"                                  => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS BOX"                                      => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS CD STATION (NON-CIRCULATING)"             => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS OFFICE"                                   => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS RARE 1 (NON-CIRCULATING)"                 => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS RARE 3 (NON-CIRCULATING)"                 => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS RARE 5 (NON-CIRCULATING)"                 => 'BVAU-MN',
        "MAIN LIBRARY FINE ARTS REFERENCE (NON-CIRCULATING)"              => 'BVAU-MN',
        "MAIN LIBRARY ADMINISTRATION"                                     => 'BVAU-MN',
        "MAIN LIBRARY JUVENILE"                                           => 'BVAU-MN',
        "MAIN LIBRARY OVERSIZE"                                           => 'BVAU-MN',
        "MAIN LIBRARY RIDINGTON ROOM"                                     => 'BVAU-MN',
        "MAIN LIBRARY WILSON COMPACT DISC"                                => 'BVAU-MN',
        "MAIN LIBRARY CIRCULATION DESK"                                   => 'BVAU-MN',
        "RARE BOOKS & SPECIAL COLLECTIONS CIRCULATION DESK"               => 'BVAU-MN',
        "MAIN LIBRARY DAMAGED"                                            => 'BVAU-MN',
        "RARE BOOKS & SPECIAL COLLECTIONS DAMAGED"                        => 'BVAU-MN',
        "MUSIC LIBRARY STACKS"                                            => 'BVAU-MUS',
        "MUSIC LIBRARY CD STATION"                                        => 'BVAU-MUS',
        "MUSIC LIBRARY REFERENCE (NON-CIRCULATING)"                       => 'BVAU-MUS',
        "MUSIC LIBRARY STAFF AREA"                                        => 'BVAU-MUS',
        "MUSIC LIBRARY OVERSIZE"                                          => 'BVAU-MUS',
        "MUSIC LIBRARY AUDIO CASSETTES"                                   => 'BVAU-MUS',
        "MUSIC LIBRARY COMPACT DISC"                                      => 'BVAU-MUS',
        "MUSIC LIBRARY PERFORMANCE"                                       => 'BVAU-MUS',
        "MUSIC LIBRARY SEMINAR ROOM"                                      => 'BVAU-MUS',
        "MUSIC LIBRARY PREBINDERY"                                        => 'BVAU-MUS',
        "MUSIC LIBRARY CIRCULATION DESK"                                  => 'BVAU-MUS',
        "MUSIC LIBRARY RESERVE COLLECTION"                                => 'BVAU-MUS',
        "MUSIC LIBRARY DAMAGED"                                           => 'BVAU-MUS',
        "ROBSON SQUARE LIBRARY STACKS"                                    => 'BVAU-RSQ',
        "ROBSON SQUARE LIBRARY AUDIO-VISUAL"                              => 'BVAU-RSQ',
        "ROBSON SQUARE LIBRARY REFERENCE (NON-CIRCULATING)"               => 'BVAU-RSQ',
        "ROBSON SQUARE LIBRARY JOURNALS"                                  => 'BVAU-RSQ',
        "ROBSON SQUARE LIBRARY NEWSPAPERS"                                => 'BVAU-RSQ',
        "ROBSON SQUARE LIBRARY CIRCULATION DESK"                          => 'BVAU-RSQ',
        "ROBSON SQUARE LIBRARY RESERVE COLLECTION"                        => 'BVAU-RSQ',
        "ROBSON SQUARE LIBRARY DAMAGED"                                   => 'BVAU-RSQ',
        "ST. PAUL'S HOSPITAL LIBRARY STACKS"                              => 'BVAU-STP',
        "ST PAUL'S HOSPITAL LIBRARY CIRCULATION DESK"                     => 'BVAU-STP',
        "ST. PAUL'S HOSPITAL LIBRARY REFERENCE (NON-CIRCULATING)"         => 'BVAU-STP',
        "ST. PAUL'S HOSPITAL LIBRARY PAMPHLET FILES"                      => 'BVAU-STP',
        "ST. PAUL'S HOSPITAL LIBRARY JOURNALS (NON-CIRCULATING)"          => 'BVAU-STP',
        "ST. PAUL'S HOSPITAL LIBRARY RESERVE COLLECTION (1 DAY LOAN)"     => 'BVAU-STP',
        "ST. PAUL'S HOSPITAL LIBRARY DONATED COLLECTIONS"                 => 'BVAU-STP',
        "ST. PAUL'S HOSPITAL LIBRARY DAMAGED"                             => 'BVAU-STP',
        "WOODWARD LIBRARY STORAGE (WD2)"                                  => 'BVAUW',
        "KOERNER LIBRARY STORAGE (FLOOR 3)"                               => 'BVAUW',
        "WOODWARD LIBRARY STACKS"                                         => 'BVAUW',
        "WOODWARD LIBRARY AUDIO-VISUAL"                                   => 'BVAUW',
        "WOODWARD LIBRARY CD STATION"                                     => 'BVAUW',
        "WOODWARD LIBRARY VERTICAL FILE"                                  => 'BVAUW',
        "WOODWARD LIBRARY GOV PUBS"                                       => 'BVAUW',
        "WOODWARD LIBRARY BIBLIOGRAPHIC CENTRE"                           => 'BVAUW',
        "WOODWARD LIBRARY MEMORIAL ROOM RARE"                             => 'BVAUW',
        "WOODWARD LIBRARY MEMORIAL ROOM EXTENSION"                        => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE DICTIONARY"                           => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE DIRECTORY"                            => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE STATISTICS"                           => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE GOV PUBS"                             => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE INFORMATION DESK"                     => 'BVAUW',
        "WOODWARD LIBRARY LOWER LEVEL"                                    => 'BVAUW',
        "WOODWARD LIBRARY CURRENT JOURNALS"                               => 'BVAUW',
        "WOODWARD LIBRARY CIRCULATION DESK"                               => 'BVAUW',
        "WOODWARD LIBRARY MEMORIAL ROOM"                                  => 'BVAUW',
        "WOODWARD LIBRARY MEMORIAL ROOM HAWTHORN COLLECTION"              => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE (NON-CIRCULATING)"                    => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE CONSUMER HEALTH"                      => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE ENCYCLOPAEDIAS"                       => 'BVAUW',
        "WOODWARD LIBRARY REFERENCE INTERLIBRARY LOANS"                   => 'BVAUW',
        "WOODWARD LIBRARY STAFF AREA"                                     => 'BVAUW',
        "WOODWARD LIBRARY STORAGE (WD1)"                                  => 'BVAUW',
        "WOODWARD LIBRARY STORAGE (WD3)"                                  => 'BVAUW',
        "WOODWARD LIBRARY RESERVE COLLECTION"                             => 'BVAUW',
        "WOODWARD LIBRARY DAMAGED"                                        => 'BVAUW',
        "WOODWARD LIBRARY LIBRARIANS' SHELF"                              => 'BVAUW',
    );

    return %map;

}

sub _call_number_field {
    return '090';
}

sub _call_number_subfield {
    return qw(a b);

}



1;
